Revert "updating workflow"
This reverts commit 613597e8c562704b35f964aa34acb628d18c8451.

diff --git a/.github/workflows/sanity_content.yml b/.github/workflows/sanity_content.yml
--- a/.github/workflows/sanity_content.yml
+++ b/.github/workflows/sanity_content.yml
@@ -9,5 +9,11 @@ jobs:
     steps:
       - name: Extract Event Type from Payload
         id: extract_event
-        run: echo "${{ github.event.client_payload}}"
+        run: echo "::set-output name=event::$(echo ${{ github.event.client_payload.event_type }} | tr -d '\"')"
 
+      - name: Check if Event Type is Valid
+        run: |
+          if [ "${{ steps.extract_event.outputs.event }}" != "sanity_content_changed" ]; then
+            echo "Invalid event type. Exiting..."
+            exit 1
+          fi
